import AppKit

enum InsertionResult: Equatable {
    case inserted
    case targetNotActivated
    case noTextInput
}

protocol TextInserting {
    func insert(_ text: String, into target: InsertionTarget, shouldSendAfterInsert: Bool) async -> InsertionResult
}

protocol ApplicationActivating {
    func activate(_ target: InsertionTarget) async -> Bool
}

protocol PasteShortcutPosting {
    func postPasteShortcut()
}

struct WorkspaceApplicationActivator: ApplicationActivating {
    private let pollInterval: Duration = .milliseconds(50)
    private let maxPolls = 20

    func activate(_ target: InsertionTarget) async -> Bool {
        guard let app = NSRunningApplication(processIdentifier: target.processIdentifier), !app.isTerminated else {
            return false
        }
        if isFrontmost(target) {
            return true
        }
        app.activate()
        for _ in 0..<maxPolls {
            try? await Task.sleep(for: pollInterval)
            if isFrontmost(target) {
                return true
            }
            if app.isTerminated || Task.isCancelled {
                return false
            }
        }
        return false
    }

    private func isFrontmost(_ target: InsertionTarget) -> Bool {
        NSWorkspace.shared.frontmostApplication?.processIdentifier == target.processIdentifier
    }
}

struct CGEventPasteShortcutPoster: PasteShortcutPosting {
    private let vKeyCode: CGKeyCode = 9

    func postPasteShortcut() {
        let source = CGEventSource(stateID: .combinedSessionState)
        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false)
        else { return }
        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        keyDown.post(tap: .cghidEventTap)
        keyUp.post(tap: .cghidEventTap)
    }
}

/// クリップボード経由(⌘V の送出)で挿入し、元のクリップボードを全データ型ごと戻す。
final class ClipboardTextInserter: TextInserting {
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private let pasteboard: NSPasteboard
    private let activator: ApplicationActivating
    private let poster: PasteShortcutPosting
    private let focusInspector: FocusedTextInputInspecting
    private let submitSender: SubmitKeySending
    private let submitDelay: Duration
    private let settleDelay: Duration
    private let restoreDelay: Duration

    private var tail: Task<InsertionResult, Never>?

    init(
        pasteboard: NSPasteboard = .general,
        activator: ApplicationActivating = WorkspaceApplicationActivator(),
        poster: PasteShortcutPosting = CGEventPasteShortcutPoster(),
        focusInspector: FocusedTextInputInspecting = AXFocusedTextInputInspector(),
        submitSender: SubmitKeySending = EnterKeySender(),
        submitDelay: Duration = .milliseconds(80),
        settleDelay: Duration = .milliseconds(50),
        restoreDelay: Duration = .milliseconds(500)
    ) {
        self.pasteboard = pasteboard
        self.activator = activator
        self.poster = poster
        self.focusInspector = focusInspector
        self.submitSender = submitSender
        self.submitDelay = submitDelay
        self.settleDelay = settleDelay
        self.restoreDelay = restoreDelay
    }

    func insert(_ text: String, into target: InsertionTarget, shouldSendAfterInsert: Bool) async -> InsertionResult {
        let previous = tail
        let task = Task {
            _ = await previous?.value
            return await self.performInsertion(text, into: target, shouldSendAfterInsert: shouldSendAfterInsert)
        }
        tail = task
        return await task.value
    }

    private func performInsertion(
        _ text: String,
        into target: InsertionTarget,
        shouldSendAfterInsert: Bool
    ) async -> InsertionResult {
        guard await activator.activate(target) else {
            return .targetNotActivated
        }
        try? await Task.sleep(for: settleDelay)

        if focusInspector.focusedTextInputState(in: target) == .notTextInput {
            return .noTextInput
        }

        let snapshot = PasteboardSnapshot.capture(from: pasteboard)
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: Self.transientType)
        item.setData(Data(), forType: Self.autoGeneratedType)
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        let changeCountAfterWrite = pasteboard.changeCount

        poster.postPasteShortcut()

        if shouldSendAfterInsert {
            try? await Task.sleep(for: submitDelay)
            await submitSender.sendSubmitKey(to: target)
        }

        try? await Task.sleep(for: restoreDelay)

        if pasteboard.changeCount == changeCountAfterWrite {
            snapshot.restore(to: pasteboard)
        }
        return .inserted
    }
}
