import AppKit
import Testing
@testable import TatakiNote

@MainActor
final class ActivatorStub: ApplicationActivating {
    var result: Bool
    var onActivate: (() -> Void)?
    private(set) var targets: [InsertionTarget] = []

    init(result: Bool) {
        self.result = result
    }

    func activate(_ target: InsertionTarget) async -> Bool {
        targets.append(target)
        onActivate?()
        return result
    }
}

@MainActor
final class PasteShortcutPosterStub: PasteShortcutPosting {
    struct Record {
        var itemCount: Int
        var types: Set<NSPasteboard.PasteboardType>
        var string: String?
    }

    private let pasteboard: NSPasteboard
    var onPost: (() -> Void)?
    private(set) var records: [Record] = []

    init(pasteboard: NSPasteboard) {
        self.pasteboard = pasteboard
    }

    func postPasteShortcut() {
        let items = pasteboard.pasteboardItems ?? []
        records.append(
            Record(
                itemCount: items.count,
                types: Set(items.flatMap(\.types)),
                string: pasteboard.string(forType: .string)
            )
        )
        onPost?()
    }
}

@MainActor
final class FocusInspectorStub: FocusedTextInputInspecting {
    var state: FocusedTextInputState
    var onInspect: (() -> Void)?
    private(set) var targets: [InsertionTarget] = []

    init(state: FocusedTextInputState) {
        self.state = state
    }

    func focusedTextInputState(in target: InsertionTarget) -> FocusedTextInputState {
        targets.append(target)
        onInspect?()
        return state
    }
}

@MainActor
final class InsertionEventLog {
    private(set) var events: [String] = []

    func add(_ event: String) {
        events.append(event)
    }

    func index(of event: String, after start: Int = -1) -> Int? {
        events.indices.first { $0 > start && events[$0] == event }
    }
}

@MainActor
final class RecordingSnapshotter: PasteboardSnapshotting {
    private let inner: BackgroundPasteboardSnapshotter
    private let log: InsertionEventLog?
    var captureDelay: Duration = .zero
    var afterCapture: ((_ callNumber: Int) -> Void)?
    private(set) var captureCount = 0
    private(set) var returnedCaptures: [CapturedPasteboard] = []
    private(set) var restoreResults: [Bool] = []

    init(pasteboard: NSPasteboard, log: InsertionEventLog? = nil) {
        inner = BackgroundPasteboardSnapshotter(pasteboard: pasteboard)
        self.log = log
    }

    func capture() async -> CapturedPasteboard {
        captureCount += 1
        let callNumber = captureCount
        log?.add("captureStart")
        if captureDelay > .zero {
            try? await Task.sleep(for: captureDelay)
        }
        let captured = await inner.capture()
        returnedCaptures.append(captured)
        afterCapture?(callNumber)
        log?.add("captureEnd")
        return captured
    }

    func restore(_ snapshot: PasteboardSnapshot, ifChangeCountIs changeCount: Int) async -> Bool {
        let didRestore = await inner.restore(snapshot, ifChangeCountIs: changeCount)
        restoreResults.append(didRestore)
        log?.add("restore")
        return didRestore
    }
}

@MainActor
final class SubmitKeySenderStub: SubmitKeySending {
    struct Record {
        var target: InsertionTarget
        var pasteboardString: String?
    }

    private let pasteboard: NSPasteboard
    var onSend: (() -> Void)?
    private(set) var records: [Record] = []

    init(pasteboard: NSPasteboard) {
        self.pasteboard = pasteboard
    }

    func sendSubmitKey(to target: InsertionTarget) async {
        records.append(Record(target: target, pasteboardString: pasteboard.string(forType: .string)))
        onSend?()
    }
}

@MainActor
struct ClipboardTextInserterTests {
    private let target = InsertionTarget(processIdentifier: 101, bundleIdentifier: "com.apple.TextEdit", localizedName: "TextEdit")
    private let markerTypes: Set<NSPasteboard.PasteboardType> = [
        .string,
        ClipboardTextInserter.transientType,
        ClipboardTextInserter.autoGeneratedType,
    ]

    private func makeInserter(
        pasteboard: NSPasteboard,
        activator: ActivatorStub,
        poster: PasteShortcutPosterStub,
        focusInspector: FocusInspectorStub? = nil,
        submitSender: SubmitKeySenderStub? = nil,
        settleDelay: Duration = .zero,
        restoreDelay: Duration = .zero,
        snapshotter: PasteboardSnapshotting? = nil
    ) -> ClipboardTextInserter {
        ClipboardTextInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            focusInspector: focusInspector ?? FocusInspectorStub(state: .textInput),
            submitSender: submitSender ?? SubmitKeySenderStub(pasteboard: pasteboard),
            submitDelay: .zero,
            settleDelay: settleDelay,
            restoreDelay: restoreDelay,
            snapshotter: snapshotter
        )
    }

    private func writeContents(_ number: Int, to pasteboard: NSPasteboard) -> PasteboardSnapshot {
        let first = NSPasteboardItem()
        first.setString("copied \(number)", forType: .string)
        first.setData(Data("{\\rtf1 copied \(number)}".utf8), forType: .rtf)
        first.setData(Data([UInt8(number), 0xFE]), forType: PasteboardFixture.customType)
        let second = NSPasteboardItem()
        second.setData(Data([0x89, 0x50, 0x4E, 0x47, UInt8(number)]), forType: .png)
        pasteboard.clearContents()
        pasteboard.writeObjects([first, second])
        return PasteboardSnapshot.capture(from: pasteboard)
    }

    @Test("AC-11, AC-12: ⌘V の時点では文章と一時的な内容の印だけが入り、終わった後に元の内容に戻る")
    func pastesOnlyTextAndMarkersThenRestores() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster)

        let result = await inserter.insert("line1\nline2", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(activator.targets == [target])
        #expect(poster.records.count == 1)
        #expect(poster.records.first?.itemCount == 1)
        #expect(poster.records.first?.types == markerTypes)
        #expect(poster.records.first?.string == "line1\nline2")
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("AC-9: 挿入先を前面にできなければ ⌘V を送らず、クリップボードも変えない")
    func doesNotTouchPasteboardWhenActivationFails() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let changeCountBefore = pasteboard.changeCount
        let activator = ActivatorStub(result: false)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster)

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .targetNotActivated)
        #expect(poster.records.isEmpty)
        #expect(pasteboard.changeCount == changeCountBefore)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("挿入先で入力欄が選ばれていなければ ⌘V を送らず、クリップボードも変えない")
    func doesNotPasteWhenNoTextInputIsFocused() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let changeCountBefore = pasteboard.changeCount
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let focusInspector = FocusInspectorStub(state: .notTextInput)
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster, focusInspector: focusInspector)

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .noTextInput)
        #expect(focusInspector.targets == [target])
        #expect(poster.records.isEmpty)
        #expect(pasteboard.changeCount == changeCountBefore)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("入力欄が選ばれているか分からなければ、今までどおり ⌘V を送る")
    func pastesWhenFocusIsUnknown() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            focusInspector: FocusInspectorStub(state: .unknown)
        )

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(poster.records.first?.string == "text")
    }

    @Test("AC-13: 挿入の途中で他のアプリがクリップボードを書き換えたら、元の内容で上書きしない")
    func doesNotOverwriteWhenPasteboardChangedMeanwhile() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        poster.onPost = {
            pasteboard.clearContents()
            pasteboard.setString("copied by someone else", forType: .string)
        }
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster)

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(pasteboard.string(forType: .string) == "copied by someone else")
        #expect(pasteboard.pasteboardItems?.count == 1)
    }

    @Test("AC-14: 前の挿入が終わる前に次の挿入を始めても、前の挿入の復元の後に始まり、最後に元の内容に戻る")
    func overlappingInsertionsAreSerialized() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)

        let activator = ActivatorStub(result: true)
        var snapshotsAtActivation: [PasteboardSnapshot] = []
        activator.onActivate = {
            snapshotsAtActivation.append(PasteboardSnapshot.capture(from: pasteboard))
        }
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            restoreDelay: .milliseconds(100)
        )
        var secondInsertion: Task<InsertionResult, Never>?
        poster.onPost = {
            guard secondInsertion == nil else { return }
            secondInsertion = Task { await inserter.insert("second", into: target, shouldSendAfterInsert: false) }
        }

        let firstResult = await inserter.insert("first", into: target, shouldSendAfterInsert: false)
        let secondResult = await secondInsertion?.value

        #expect(firstResult == .inserted)
        #expect(secondResult == .inserted)
        #expect(activator.targets.count == 2)
        #expect(snapshotsAtActivation.count == 2)
        #expect(snapshotsAtActivation.last == original)
        #expect(poster.records.count == 2)
        #expect(poster.records.first?.string == "first")
        #expect(poster.records.last?.string == "second")
        #expect(poster.records.last?.types == markerTypes)
        #expect(poster.records.last?.itemCount == 1)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    // MARK: - 確定+送信

    @Test("AC-4: 確定+送信では、⌘V の後(クリップボードを戻す前)に挿入先へ Enter が1回だけ送られ、最後に元の内容に戻る")
    func sendsSubmitKeyOnceAfterPaste() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
        var pasteCountsWhenSent: [Int] = []
        submitSender.onSend = { pasteCountsWhenSent.append(poster.records.count) }
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster, submitSender: submitSender)

        let result = await inserter.insert("hello", into: target, shouldSendAfterInsert: true)

        #expect(result == .inserted)
        #expect(poster.records.count == 1)
        #expect(submitSender.records.count == 1)
        #expect(pasteCountsWhenSent == [1])
        #expect(submitSender.records.first?.target == target)
        #expect(submitSender.records.first?.pasteboardString == "hello")
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("AC-4: 確定(送信しない)では、⌘V は送るが Enter は送らない")
    func doesNotSendSubmitKeyForCommitOnly() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster, submitSender: submitSender)

        let result = await inserter.insert("hello", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(poster.records.count == 1)
        #expect(submitSender.records.isEmpty)
    }

    @Test("AC-5: 確定+送信でも、挿入先を前面にできない・入力欄でないと分かったときは、⌘V も Enter も送らず、クリップボードも変えない")
    func doesNotPasteOrSendWhenInsertionIsNotPossible() async {
        let scenarios: [(String, Bool, FocusedTextInputState, InsertionResult)] = [
            ("前面にできない", false, .textInput, .targetNotActivated),
            ("入力欄でない", true, .notTextInput, .noTextInput),
        ]
        for (name, canActivate, focusState, expectedResult) in scenarios {
            let pasteboard = PasteboardFixture.makePasteboard()
            defer { pasteboard.releaseGlobally() }
            PasteboardFixture.writeRichContents(to: pasteboard)
            let original = PasteboardSnapshot.capture(from: pasteboard)
            let changeCountBefore = pasteboard.changeCount
            let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
            let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
            let inserter = makeInserter(
                pasteboard: pasteboard,
                activator: ActivatorStub(result: canActivate),
                poster: poster,
                focusInspector: FocusInspectorStub(state: focusState),
                submitSender: submitSender
            )

            let result = await inserter.insert("hello", into: target, shouldSendAfterInsert: true)

            #expect(result == expectedResult, "\(name)")
            #expect(poster.records.isEmpty, "\(name)")
            #expect(submitSender.records.isEmpty, "\(name)")
            #expect(pasteboard.changeCount == changeCountBefore, "\(name)")
            #expect(PasteboardSnapshot.capture(from: pasteboard) == original, "\(name)")
        }
    }

    @Test("AC-13: 入力欄かどうか分からないアプリでは、確定+送信で今までどおり ⌘V を送り、Enter も送る")
    func pastesAndSendsWhenFocusIsUnknown() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            focusInspector: FocusInspectorStub(state: .unknown),
            submitSender: submitSender
        )

        let result = await inserter.insert("hello", into: target, shouldSendAfterInsert: true)

        #expect(result == .inserted)
        #expect(poster.records.first?.string == "hello")
        #expect(submitSender.records.count == 1)
        #expect(submitSender.records.first?.target == target)
    }

    // MARK: - 写し取りと書き戻し

    @Test("AC-4: 写し取りは挿入先を前面にした後・入力欄の判定より前に始まり、⌘V は写し取りが終わってから送られる")
    func capturesDuringSettleDelayAndPastesAfterCaptureFinishes() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let log = InsertionEventLog()
        let activator = ActivatorStub(result: true)
        activator.onActivate = { log.add("activate") }
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        poster.onPost = { log.add("paste") }
        let focusInspector = FocusInspectorStub(state: .textInput)
        focusInspector.onInspect = { log.add("inspect") }
        let snapshotter = RecordingSnapshotter(pasteboard: pasteboard, log: log)
        snapshotter.captureDelay = .milliseconds(100)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            focusInspector: focusInspector,
            settleDelay: .milliseconds(30),
            snapshotter: snapshotter
        )

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        let activate = log.index(of: "activate")
        let captureStart = log.index(of: "captureStart")
        let inspect = log.index(of: "inspect")
        let captureEnd = log.index(of: "captureEnd")
        let paste = log.index(of: "paste")
        #expect(activate != nil && captureStart != nil && inspect != nil && captureEnd != nil && paste != nil)
        if let activate, let captureStart, let inspect, let captureEnd, let paste {
            #expect(activate < captureStart)
            #expect(captureStart < inspect)
            #expect(captureEnd < paste)
        }
        #expect(snapshotter.captureCount == 1)
        #expect(poster.records.count == 1)
    }

    @Test("AC-5: 写し取りの後・貼り付けの前に別の内容がコピーされたら写し直し、挿入の後にその新しい内容に戻る")
    func recapturesWhenPasteboardChangedAfterCapture() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let snapshotter = RecordingSnapshotter(pasteboard: pasteboard)
        var rewritten: PasteboardSnapshot?
        snapshotter.afterCapture = { callNumber in
            guard callNumber == 1 else { return }
            rewritten = self.writeContents(7, to: pasteboard)
        }
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: ActivatorStub(result: true),
            poster: poster,
            snapshotter: snapshotter
        )

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(snapshotter.captureCount == 2)
        #expect(poster.records.count == 1)
        #expect(poster.records.first?.string == "text")
        #expect(rewritten != nil)
        #expect(snapshotter.returnedCaptures.last?.snapshot == rewritten)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == rewritten)
    }

    @Test("AC-6: 入力欄でないと分かったときは、写し取りを待ってから ⌘V を送らずに終わり、クリップボードも変更回数も変えない")
    func waitsForCaptureAndLeavesPasteboardWhenNoTextInput() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let changeCountBefore = pasteboard.changeCount
        let log = InsertionEventLog()
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let snapshotter = RecordingSnapshotter(pasteboard: pasteboard, log: log)
        snapshotter.captureDelay = .milliseconds(100)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: ActivatorStub(result: true),
            poster: poster,
            focusInspector: FocusInspectorStub(state: .notTextInput),
            settleDelay: .milliseconds(10),
            snapshotter: snapshotter
        )

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: true)

        #expect(result == .noTextInput)
        #expect(snapshotter.captureCount == 1)
        #expect(log.events == ["captureStart", "captureEnd"])
        #expect(poster.records.isEmpty)
        #expect(snapshotter.restoreResults.isEmpty)
        #expect(pasteboard.changeCount == changeCountBefore)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("AC-6: 挿入先を前面にできないときは、写し取りも始めない")
    func doesNotStartCaptureWhenActivationFails() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let changeCountBefore = pasteboard.changeCount
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let snapshotter = RecordingSnapshotter(pasteboard: pasteboard)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: ActivatorStub(result: false),
            poster: poster,
            snapshotter: snapshotter
        )

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .targetNotActivated)
        #expect(snapshotter.captureCount == 0)
        #expect(poster.records.isEmpty)
        #expect(pasteboard.changeCount == changeCountBefore)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("AC-7: 背景で写し取り・書き戻しをしても、⌘V の時点では文章と印だけが入り、終わった後に元の内容に戻る")
    func pastesOnlyTextAndMarkersWithBackgroundSnapshotting() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let snapshotter = RecordingSnapshotter(pasteboard: pasteboard)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: ActivatorStub(result: true),
            poster: poster,
            snapshotter: snapshotter
        )

        let result = await inserter.insert("line1\nline2", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(poster.records.count == 1)
        #expect(poster.records.first?.itemCount == 1)
        #expect(poster.records.first?.types == markerTypes)
        #expect(poster.records.first?.string == "line1\nline2")
        #expect(snapshotter.restoreResults == [true])
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("AC-7: ⌘V や Enter の後、元に戻すまでの間に他のアプリがコピーしたら、元に戻さない")
    func doesNotRestoreWhenCopiedAfterPasteOrSubmit() async {
        let scenarios: [(String, Bool)] = [("確定", false), ("確定+送信", true)]
        for (name, shouldSend) in scenarios {
            let pasteboard = PasteboardFixture.makePasteboard()
            defer { pasteboard.releaseGlobally() }
            PasteboardFixture.writeRichContents(to: pasteboard)
            let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
            let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
            let snapshotter = RecordingSnapshotter(pasteboard: pasteboard)
            let copyByOtherApp = {
                pasteboard.clearContents()
                pasteboard.setString("copied by someone else", forType: .string)
            }
            if shouldSend {
                submitSender.onSend = copyByOtherApp
            } else {
                poster.onPost = copyByOtherApp
            }
            let inserter = makeInserter(
                pasteboard: pasteboard,
                activator: ActivatorStub(result: true),
                poster: poster,
                submitSender: submitSender,
                snapshotter: snapshotter
            )

            let result = await inserter.insert("text", into: target, shouldSendAfterInsert: shouldSend)

            #expect(result == .inserted, "\(name)")
            #expect(snapshotter.restoreResults == [false], "\(name)")
            #expect(pasteboard.string(forType: .string) == "copied by someone else", "\(name)")
            #expect(pasteboard.pasteboardItems?.count == 1, "\(name)")
        }
    }

    @Test("AC-7: 続けて確定したときは、前の挿入で元に戻し終えてから次が始まる")
    func serializesInsertionsWithBackgroundSnapshotting() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let log = InsertionEventLog()
        let activator = ActivatorStub(result: true)
        activator.onActivate = { log.add("activate") }
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let snapshotter = RecordingSnapshotter(pasteboard: pasteboard, log: log)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            restoreDelay: .milliseconds(50),
            snapshotter: snapshotter
        )
        var secondInsertion: Task<InsertionResult, Never>?
        poster.onPost = {
            guard secondInsertion == nil else { return }
            secondInsertion = Task { await inserter.insert("second", into: target, shouldSendAfterInsert: false) }
        }

        let firstResult = await inserter.insert("first", into: target, shouldSendAfterInsert: false)
        let secondResult = await secondInsertion?.value

        #expect(firstResult == .inserted)
        #expect(secondResult == .inserted)
        #expect(poster.records.map(\.string) == ["first", "second"])
        #expect(snapshotter.restoreResults == [true, true])
        let firstRestore = log.index(of: "restore")
        let secondActivate = log.index(of: "activate", after: 0)
        #expect(firstRestore != nil && secondActivate != nil)
        if let firstRestore, let secondActivate {
            #expect(firstRestore < secondActivate)
        }
        #expect(snapshotter.returnedCaptures.last?.snapshot == original)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("AC-14: 写し取るたびにクリップボードが変わり続けても、写し直しは3回で止まり、⌘V は1回送られ、最後に写し取った内容に戻る", .timeLimit(.minutes(1)))
    func stopsRecapturingAtLimitWhenPasteboardKeepsChanging() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let snapshotter = RecordingSnapshotter(pasteboard: pasteboard)
        var written: [PasteboardSnapshot] = []
        snapshotter.afterCapture = { callNumber in
            written.append(self.writeContents(callNumber, to: pasteboard))
        }
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: ActivatorStub(result: true),
            poster: poster,
            snapshotter: snapshotter
        )

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(snapshotter.captureCount == 4)
        #expect(poster.records.count == 1)
        #expect(poster.records.first?.string == "text")
        #expect(written.count == 4)
        if written.count == 4 {
            #expect(snapshotter.returnedCaptures.last?.snapshot == written[2])
            #expect(PasteboardSnapshot.capture(from: pasteboard) == written[2])
        }
    }
}
