import AppKit
import Testing
@testable import TatakiNote

@MainActor
final class ActivatorStub: ApplicationActivating {
    var result: Bool
    var onActivate: (() -> Void)?
    private(set) var targets: [InsertionTarget] = []

    init(result: Bool) {
        self.result = result
    }

    func activate(_ target: InsertionTarget) async -> Bool {
        targets.append(target)
        onActivate?()
        return result
    }
}

@MainActor
final class PasteShortcutPosterStub: PasteShortcutPosting {
    struct Record {
        var itemCount: Int
        var types: Set<NSPasteboard.PasteboardType>
        var string: String?
    }

    private let pasteboard: NSPasteboard
    var onPost: (() -> Void)?
    private(set) var records: [Record] = []

    init(pasteboard: NSPasteboard) {
        self.pasteboard = pasteboard
    }

    func postPasteShortcut() {
        let items = pasteboard.pasteboardItems ?? []
        records.append(
            Record(
                itemCount: items.count,
                types: Set(items.flatMap(\.types)),
                string: pasteboard.string(forType: .string)
            )
        )
        onPost?()
    }
}

@MainActor
final class FocusInspectorStub: FocusedTextInputInspecting {
    var state: FocusedTextInputState
    private(set) var targets: [InsertionTarget] = []

    init(state: FocusedTextInputState) {
        self.state = state
    }

    func focusedTextInputState(in target: InsertionTarget) -> FocusedTextInputState {
        targets.append(target)
        return state
    }
}

@MainActor
final class SubmitKeySenderStub: SubmitKeySending {
    struct Record {
        var target: InsertionTarget
        var pasteboardString: String?
    }

    private let pasteboard: NSPasteboard
    var onSend: (() -> Void)?
    private(set) var records: [Record] = []

    init(pasteboard: NSPasteboard) {
        self.pasteboard = pasteboard
    }

    func sendSubmitKey(to target: InsertionTarget) async {
        records.append(Record(target: target, pasteboardString: pasteboard.string(forType: .string)))
        onSend?()
    }
}

@MainActor
struct ClipboardTextInserterTests {
    private let target = InsertionTarget(processIdentifier: 101, bundleIdentifier: "com.apple.TextEdit", localizedName: "TextEdit")
    private let markerTypes: Set<NSPasteboard.PasteboardType> = [
        .string,
        ClipboardTextInserter.transientType,
        ClipboardTextInserter.autoGeneratedType,
    ]

    private func makeInserter(
        pasteboard: NSPasteboard,
        activator: ActivatorStub,
        poster: PasteShortcutPosterStub,
        focusInspector: FocusInspectorStub? = nil,
        submitSender: SubmitKeySenderStub? = nil,
        restoreDelay: Duration = .zero
    ) -> ClipboardTextInserter {
        ClipboardTextInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            focusInspector: focusInspector ?? FocusInspectorStub(state: .textInput),
            submitSender: submitSender ?? SubmitKeySenderStub(pasteboard: pasteboard),
            submitDelay: .zero,
            settleDelay: .zero,
            restoreDelay: restoreDelay
        )
    }

    @Test("AC-11, AC-12: ⌘V の時点では文章と一時的な内容の印だけが入り、終わった後に元の内容に戻る")
    func pastesOnlyTextAndMarkersThenRestores() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster)

        let result = await inserter.insert("line1\nline2", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(activator.targets == [target])
        #expect(poster.records.count == 1)
        #expect(poster.records.first?.itemCount == 1)
        #expect(poster.records.first?.types == markerTypes)
        #expect(poster.records.first?.string == "line1\nline2")
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("AC-9: 挿入先を前面にできなければ ⌘V を送らず、クリップボードも変えない")
    func doesNotTouchPasteboardWhenActivationFails() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let changeCountBefore = pasteboard.changeCount
        let activator = ActivatorStub(result: false)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster)

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .targetNotActivated)
        #expect(poster.records.isEmpty)
        #expect(pasteboard.changeCount == changeCountBefore)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("挿入先で入力欄が選ばれていなければ ⌘V を送らず、クリップボードも変えない")
    func doesNotPasteWhenNoTextInputIsFocused() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let changeCountBefore = pasteboard.changeCount
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let focusInspector = FocusInspectorStub(state: .notTextInput)
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster, focusInspector: focusInspector)

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .noTextInput)
        #expect(focusInspector.targets == [target])
        #expect(poster.records.isEmpty)
        #expect(pasteboard.changeCount == changeCountBefore)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("入力欄が選ばれているか分からなければ、今までどおり ⌘V を送る")
    func pastesWhenFocusIsUnknown() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            focusInspector: FocusInspectorStub(state: .unknown)
        )

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(poster.records.first?.string == "text")
    }

    @Test("AC-13: 挿入の途中で他のアプリがクリップボードを書き換えたら、元の内容で上書きしない")
    func doesNotOverwriteWhenPasteboardChangedMeanwhile() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        poster.onPost = {
            pasteboard.clearContents()
            pasteboard.setString("copied by someone else", forType: .string)
        }
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster)

        let result = await inserter.insert("text", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(pasteboard.string(forType: .string) == "copied by someone else")
        #expect(pasteboard.pasteboardItems?.count == 1)
    }

    @Test("AC-14: 前の挿入が終わる前に次の挿入を始めても、前の挿入の復元の後に始まり、最後に元の内容に戻る")
    func overlappingInsertionsAreSerialized() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)

        let activator = ActivatorStub(result: true)
        var snapshotsAtActivation: [PasteboardSnapshot] = []
        activator.onActivate = {
            snapshotsAtActivation.append(PasteboardSnapshot.capture(from: pasteboard))
        }
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            restoreDelay: .milliseconds(100)
        )
        var secondInsertion: Task<InsertionResult, Never>?
        poster.onPost = {
            guard secondInsertion == nil else { return }
            secondInsertion = Task { await inserter.insert("second", into: target, shouldSendAfterInsert: false) }
        }

        let firstResult = await inserter.insert("first", into: target, shouldSendAfterInsert: false)
        let secondResult = await secondInsertion?.value

        #expect(firstResult == .inserted)
        #expect(secondResult == .inserted)
        #expect(activator.targets.count == 2)
        #expect(snapshotsAtActivation.count == 2)
        #expect(snapshotsAtActivation.last == original)
        #expect(poster.records.count == 2)
        #expect(poster.records.first?.string == "first")
        #expect(poster.records.last?.string == "second")
        #expect(poster.records.last?.types == markerTypes)
        #expect(poster.records.last?.itemCount == 1)
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    // MARK: - 確定+送信

    @Test("AC-4: 確定+送信では、⌘V の後(クリップボードを戻す前)に挿入先へ Enter が1回だけ送られ、最後に元の内容に戻る")
    func sendsSubmitKeyOnceAfterPaste() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        PasteboardFixture.writeRichContents(to: pasteboard)
        let original = PasteboardSnapshot.capture(from: pasteboard)
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
        var pasteCountsWhenSent: [Int] = []
        submitSender.onSend = { pasteCountsWhenSent.append(poster.records.count) }
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster, submitSender: submitSender)

        let result = await inserter.insert("hello", into: target, shouldSendAfterInsert: true)

        #expect(result == .inserted)
        #expect(poster.records.count == 1)
        #expect(submitSender.records.count == 1)
        #expect(pasteCountsWhenSent == [1])
        #expect(submitSender.records.first?.target == target)
        #expect(submitSender.records.first?.pasteboardString == "hello")
        #expect(PasteboardSnapshot.capture(from: pasteboard) == original)
    }

    @Test("AC-4: 確定(送信しない)では、⌘V は送るが Enter は送らない")
    func doesNotSendSubmitKeyForCommitOnly() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
        let inserter = makeInserter(pasteboard: pasteboard, activator: activator, poster: poster, submitSender: submitSender)

        let result = await inserter.insert("hello", into: target, shouldSendAfterInsert: false)

        #expect(result == .inserted)
        #expect(poster.records.count == 1)
        #expect(submitSender.records.isEmpty)
    }

    @Test("AC-5: 確定+送信でも、挿入先を前面にできない・入力欄でないと分かったときは、⌘V も Enter も送らず、クリップボードも変えない")
    func doesNotPasteOrSendWhenInsertionIsNotPossible() async {
        let scenarios: [(String, Bool, FocusedTextInputState, InsertionResult)] = [
            ("前面にできない", false, .textInput, .targetNotActivated),
            ("入力欄でない", true, .notTextInput, .noTextInput),
        ]
        for (name, canActivate, focusState, expectedResult) in scenarios {
            let pasteboard = PasteboardFixture.makePasteboard()
            defer { pasteboard.releaseGlobally() }
            PasteboardFixture.writeRichContents(to: pasteboard)
            let original = PasteboardSnapshot.capture(from: pasteboard)
            let changeCountBefore = pasteboard.changeCount
            let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
            let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
            let inserter = makeInserter(
                pasteboard: pasteboard,
                activator: ActivatorStub(result: canActivate),
                poster: poster,
                focusInspector: FocusInspectorStub(state: focusState),
                submitSender: submitSender
            )

            let result = await inserter.insert("hello", into: target, shouldSendAfterInsert: true)

            #expect(result == expectedResult, "\(name)")
            #expect(poster.records.isEmpty, "\(name)")
            #expect(submitSender.records.isEmpty, "\(name)")
            #expect(pasteboard.changeCount == changeCountBefore, "\(name)")
            #expect(PasteboardSnapshot.capture(from: pasteboard) == original, "\(name)")
        }
    }

    @Test("AC-13: 入力欄かどうか分からないアプリでは、確定+送信で今までどおり ⌘V を送り、Enter も送る")
    func pastesAndSendsWhenFocusIsUnknown() async {
        let pasteboard = PasteboardFixture.makePasteboard()
        defer { pasteboard.releaseGlobally() }
        let activator = ActivatorStub(result: true)
        let poster = PasteShortcutPosterStub(pasteboard: pasteboard)
        let submitSender = SubmitKeySenderStub(pasteboard: pasteboard)
        let inserter = makeInserter(
            pasteboard: pasteboard,
            activator: activator,
            poster: poster,
            focusInspector: FocusInspectorStub(state: .unknown),
            submitSender: submitSender
        )

        let result = await inserter.insert("hello", into: target, shouldSendAfterInsert: true)

        #expect(result == .inserted)
        #expect(poster.records.first?.string == "hello")
        #expect(submitSender.records.count == 1)
        #expect(submitSender.records.first?.target == target)
    }
}
